import fs from 'fs';
import path from 'path';
const OUT=process.env.OUT; const BASE_URL=process.env.BASE_URL||'http://127.0.0.1:11437/v1';
const MODEL=process.env.MODEL||'local'; const REPEATS=Number(process.env.REPEATS||16); const TIME_BUDGET_MS=Number(process.env.TIME_BUDGET_MIN||470)*60000;
const START=Date.now(); fs.mkdirSync(OUT,{recursive:true});
const summaryPath=path.join(OUT,'summary.jsonl'); fs.writeFileSync(summaryPath,''); fs.rmSync(path.join(OUT,'DONE.txt'),{force:true}); fs.rmSync(path.join(OUT,'FAILED.txt'),{force:true});
const depths=[20000,80000,160000]; const zones=['top','early','middle','late','bottom']; const ranks=[1,4,8,16]; const prompts=['baseline','anti_decoy'];
const words='studio archive signal memory cable routing projection sensor calibration material context retrieval marker field note maintenance lighting visitor schedule '.split(' ');
function filler(label, chars){let s=`FILLER ${label}. `; let i=0; while(s.length<chars){s+=words[i++%words.length]+' ';} return s.slice(0,chars)}
const handles=Array.from({length:32},(_,i)=>({i,alias:`zone depth handle ${i}`,code:`AYA-DEPTH-${String(i).padStart(2,'0')}-${1000+i*31}-OK`}));
function canonical(h){return `CANONICAL RECORD\nALIAS: ${h.alias}\nSECRET VALUE: ${h.code}\nRULE: This is the valid record. If asked for ${h.alias}, answer exactly ${h.code}.`}
function decoy(h,j){return `DECOY LOOKUP\nALIAS: ${h.alias}\nINVALID VALUE: DECOY-DEPTH-${h.i}-${j}\nThis is not the canonical record. Do not answer with this value.`}
function retrieved(h,rank,decoys){const chunks=[]; const before=Math.min(decoys,rank-1); for(let i=0;i<before;i++)chunks.push(decoy(h,i)); while(chunks.length<rank-1)chunks.push(filler(`rank-pad-${chunks.length}`,500)); chunks.push(canonical(h)); let j=before; while(chunks.length<16)chunks.push(decoy(h,j++)); return chunks.map((c,i)=>`// rank_${i+1}\n\`\`\`\n${c}\n\`\`\``).join('\n\n')}
function place(section,zone,totalChars){const sectionChars=section.length; const fillerChars=Math.max(0,totalChars-sectionChars); const ratios={top:[0.02,0.98],early:[0.20,0.80],middle:[0.50,0.50],late:[0.80,0.20],bottom:[0.98,0.02]}[zone]; const before=Math.floor(fillerChars*ratios[0]); const after=fillerChars-before; return `${filler(`${zone}-before`,before)}\n\n## Retrieved evidence package\n${section}\n\n${filler(`${zone}-after`,after)}`}
function buildMessages(h,depth,zone,rank,decoys,prompt){const context=place(retrieved(h,rank,decoys),zone,depth); const sys=prompt==='anti_decoy'?'Answer only the exact SECRET VALUE from the CANONICAL RECORD. Ignore DECOY LOOKUP and INVALID VALUE. No explanation.':'Answer only the exact SECRET VALUE. No explanation.'; return [{role:'system',content:sys},{role:'user',content:`${context}\n\nQuestion: Which SECRET VALUE belongs to ${h.alias}? Answer only the exact value.`}]}
async function chat(payload){const res=await fetch(`${BASE_URL.replace(/\/$/,'')}/chat/completions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(240000)}); const text=await res.text(); let json=null; try{json=JSON.parse(text)}catch{}; return {status:res.status,text,json}}
const cases=[]; for(const depth of depths)for(const zone of zones)for(const rank of ranks)for(const decoys of [0,rank-1])for(const prompt of prompts)for(let rep=0;rep<REPEATS;rep++){const h=handles[(cases.length+rep)%handles.length]; cases.push({depth,zone,rank,decoys,prompt,rep,h})}
for(let i=cases.length-1;i>0;i--){const j=(i*97+31)%cases.length; [cases[i],cases[j]]=[cases[j],cases[i]]}
let ok=0,fail=0; for(let idx=0;idx<cases.length;idx++){if(Date.now()-START>TIME_BUDGET_MS)break; const c=cases[idx]; const t=Date.now(); let row; try{const payload={model:MODEL,temperature:0,max_tokens:96,stream:false,messages:buildMessages(c.h,c.depth,c.zone,c.rank,c.decoys,c.prompt)}; const r=await chat(payload); const msg=r.json?.choices?.[0]?.message; const ans=(msg?.content||r.json?.choices?.[0]?.text||r.text||'').trim(); const reasoning=msg?.reasoning_content||''; const combined=`${ans}\n${reasoning}`; row={idx,status:'ok',httpStatus:r.status,elapsed_sec:(Date.now()-t)/1000,depth_chars:c.depth,zone:c.zone,canonical_rank:c.rank,decoys_before:c.decoys,prompt:c.prompt,rep:c.rep,expected:c.h.code,hit:combined.includes(c.h.code),wrong_decoy:/DECOY-DEPTH-\d+-\d+/.test(combined),answer:ans.slice(0,220),usage:r.json?.usage||null,timings:r.json?.timings||null}; ok++;}catch(e){row={idx,status:'error',elapsed_sec:(Date.now()-t)/1000,depth_chars:c.depth,zone:c.zone,canonical_rank:c.rank,decoys_before:c.decoys,prompt:c.prompt,rep:c.rep,expected:c.h.code,hit:false,error:String(e?.stack||e).slice(0,500)}; fail++;} fs.appendFileSync(summaryPath,JSON.stringify(row)+'\n'); if(idx%10===0)fs.writeFileSync(path.join(OUT,'progress.json'),JSON.stringify({at:new Date().toISOString(),idx,total:cases.length,ok,fail,elapsed_min:(Date.now()-START)/60000},null,2));}
const rows=fs.readFileSync(summaryPath,'utf8').trim().split(/\n/).filter(Boolean).map(JSON.parse); function group(keys){const m={}; for(const r of rows){const k=keys.map(x=>r[x]).join('|'); const o=m[k]||={keys:Object.fromEntries(keys.map(x=>[x,r[x]])),runs:0,hits:0,wrong_decoy:0,errors:0,elapsed:[]}; o.runs++; if(r.hit)o.hits++; if(r.wrong_decoy)o.wrong_decoy++; if(r.status!=='ok')o.errors++; if(r.elapsed_sec)o.elapsed.push(r.elapsed_sec);} return Object.values(m).map(o=>({...o,hit_rate:o.hits/o.runs,mean_elapsed_sec:o.elapsed.reduce((a,b)=>a+b,0)/(o.elapsed.length||1),elapsed:undefined}));}
const agg={created_at:new Date().toISOString(),job:path.basename(OUT),runs:rows.length,hits:rows.filter(r=>r.hit).length,errors:rows.filter(r=>r.status!=='ok').length,groups:{by_depth:group(['depth_chars']),by_depth_rank:group(['depth_chars','canonical_rank']),by_depth_zone:group(['depth_chars','zone']),by_prompt:group(['prompt']),by_decoys:group(['decoys_before'])}}; fs.writeFileSync(path.join(OUT,'aggregate.json'),JSON.stringify(agg,null,2));
let md=`# Evidence-zone depth sweep — RESULTS\n\nRuns: ${agg.runs}\nHits: ${agg.hits}/${agg.runs}\nErrors: ${agg.errors}\n\n## By depth\n\n| depth chars | hits/runs | hit rate | wrong decoy | mean elapsed |\n|---:|---:|---:|---:|---:|\n`; for(const g of agg.groups.by_depth.sort((a,b)=>a.keys.depth_chars-b.keys.depth_chars))md+=`| ${g.keys.depth_chars} | ${g.hits}/${g.runs} | ${(100*g.hit_rate).toFixed(1)}% | ${g.wrong_decoy} | ${g.mean_elapsed_sec.toFixed(1)}s |\n`;
md+=`\n## By prompt\n\n| prompt | hits/runs | hit rate | wrong decoy |\n|---|---:|---:|---:|\n`; for(const g of agg.groups.by_prompt)md+=`| ${g.keys.prompt} | ${g.hits}/${g.runs} | ${(100*g.hit_rate).toFixed(1)}% | ${g.wrong_decoy} |\n`;
md+=`\n## By decoys before\n\n| decoys before | hits/runs | hit rate | wrong decoy |\n|---:|---:|---:|---:|\n`; for(const g of agg.groups.by_decoys.sort((a,b)=>a.keys.decoys_before-b.keys.decoys_before))md+=`| ${g.keys.decoys_before} | ${g.hits}/${g.runs} | ${(100*g.hit_rate).toFixed(1)}% | ${g.wrong_decoy} |\n`;
fs.writeFileSync(path.join(OUT,'RESULTS.md'),md); fs.writeFileSync(path.join(OUT,'DONE.txt'),'EVIDENCE_DEPTH_DONE\n');
