import fs from 'fs'; import path from 'path';
const [,, longctxPort, upstreamPort, corpus, outDir]=process.argv;
const manifest=JSON.parse(fs.readFileSync(`${corpus}/manifest.json`,'utf8'));
const readme=`${corpus}/README.md`, summary=`${outDir}/summary.jsonl`;
const handles=['brass-river-index','glass-orchid-vector','jade-winter-circuit','ceramic-lantern-field'];
const targets=manifest.targets.filter(t=>handles.includes(t.handle));
function append(o){fs.appendFileSync(summary,JSON.stringify(o)+'\n')}
function qOriginal(rec){return `Which SECRET VALUE belongs to the ${rec.alias}? The clue is ${rec.clue}.`}
function qRewrite(rec){return `Find the canonical non-decoy record for handle ${rec.handle}. Ignore all DECOY LOOKUP and INVALID VALUE lines. Return only the valid line beginning SECRET VALUE for alias ${rec.alias}. Clue: ${rec.clue}.`}
function rankChunks(chunks,rec){return chunks.map((c,i)=>({i,score:policyScore(c,rec),chunk:c})).sort((a,b)=>b.score-a.score).map(x=>x.chunk)}
function policyScore(c,rec){const t=String(c.text||'');let s=0;if(t.includes('SECRET VALUE:'))s+=10;if(t.includes('CANONICAL HANDLE:'))s+=4;if(t.includes(rec.handle))s+=4;if(t.includes(rec.alias))s+=2;if(t.includes('DECOY LOOKUP'))s-=7;if(t.includes('INVALID VALUE'))s-=5;if(t.includes(rec.code))s+=20;return s}
function contextBlock(chunks,rec){return '## Retrieved context\n\n'+rankChunks(chunks,rec).slice(0,4).map(c=>`// ${c.file_path}:${c.start_line}-${c.end_line}\n\`\`\`\n${c.text}\n\`\`\``).join('\n\n')}
async function retrieve(rec,query,label,idx){const body={session_id:`decoy-resolution-${label}`,prefill_text:`Project path: ${readme}\nQuestion: ${query}`,query,top_k:16};const res=await fetch(`http://127.0.0.1:${longctxPort}/retrieve`,{method:'POST',headers:{'content-type':'application/json','x-session-affinity':`decoy-resolution-${label}`},body:JSON.stringify(body),signal:AbortSignal.timeout(600000)});const text=await res.text();let json=null;try{json=JSON.parse(text)}catch{};const chunks=json?.chunks||[];const rank=chunks.findIndex(c=>String(c.text||'').includes(rec.code))+1;const decoysBefore=rank>0?chunks.slice(0,rank-1).filter(c=>String(c.text||'').includes('DECOY')).length:null;fs.writeFileSync(`${outDir}/retrieve/${String(idx).padStart(2,'0')}-${label}-${rec.handle}.json`,JSON.stringify({body,status:res.status,json,rank,decoysBefore,used_rerank:json?.used_rerank,paraphrases_count:json?.paraphrases_count},null,2));return{chunks,rank,decoysBefore,used_rerank:json?.used_rerank,paraphrases_count:json?.paraphrases_count,retrieval_hit:rank>0}}
async function chat(endpoint,payload,idx,arm,rec,ret){const started=Date.now();let status='ok',httpStatus=0,text='',json=null,answer='',hit=false,headers={};try{const res=await fetch(`http://127.0.0.1:${endpoint}/v1/chat/completions`,{method:'POST',headers:{'content-type':'application/json','x-session-affinity':`decoy-resolution-${arm}`},body:JSON.stringify(payload),signal:AbortSignal.timeout(300000)});httpStatus=res.status;for(const k of ['x-longctx-chunks-used','x-longctx-scope-status','x-longctx-scope','x-longctx-confidence'])headers[k]=res.headers.get(k);text=await res.text();try{json=JSON.parse(text)}catch{};const msg=json?.choices?.[0]?.message;answer=msg?.content??json?.choices?.[0]?.text??text;const reasoning=msg?.reasoning_content??'';hit=(`${answer}\n${reasoning}`).includes(rec.code);if(!answer&&reasoning)answer=`[reasoning] ${reasoning}`;if(!res.ok)status='http_error'}catch(e){status='error';text=String(e?.stack||e)}const elapsed=(Date.now()-started)/1000;fs.writeFileSync(`${outDir}/raw/${String(idx).padStart(2,'0')}-${arm}-${rec.handle}.json`,JSON.stringify({payload,headers,httpStatus,text,json,answer},null,2));append({idx,arm,handle:rec.handle,alias:rec.alias,expected:rec.code,status,httpStatus,elapsed_sec:elapsed,answer:String(answer).trim().slice(0,500),hit,headers,timings:json?.timings||null,usage:json?.usage||null,retrieval_hit:ret?.retrieval_hit??null,rank:ret?.rank??null,decoysBefore:ret?.decoysBefore??null,used_rerank:ret?.used_rerank??null,paraphrases_count:ret?.paraphrases_count??null})}
function proxyPayload(rec,query,arm){const system=arm.includes('rewrite')?'You are a precise retrieval assistant. Ignore every chunk or line marked DECOY LOOKUP, INVALID VALUE, or explicitly not the requested record. Use only a valid line beginning SECRET VALUE from the canonical non-decoy record. Answer only the exact secret value.':'You are a precise retrieval assistant. Answer only the exact secret value, no explanation.';return{model:'local',temperature:0,max_tokens:120,stream:false,longctx_top_k:16,messages:[{role:'system',content:system},{role:'user',content:`Project path: ${readme}\n${query}\nAnswer only the exact secret value.`}]}}
function manualPayload(rec,block){return{model:'local',temperature:0,max_tokens:120,stream:false,messages:[{role:'system',content:'You are a precise retrieval assistant. Answer only the exact SECRET VALUE from the non-decoy canonical record. No explanation.'},{role:'user',content:`${block}\n\nQuestion: ${qOriginal(rec)} Answer only the exact secret value.`}]}}
let idx=0;
for(const rec of targets){
 const retOrig=await retrieve(rec,qOriginal(rec),'orig-rerank',++idx);
 const retRew=await retrieve(rec,qRewrite(rec),'rewrite-rerank',++idx);
 await chat(longctxPort,proxyPayload(rec,qOriginal(rec),'rerank_proxy_orig'),++idx,'rerank_proxy_orig',rec,retOrig);
 await chat(longctxPort,proxyPayload(rec,qRewrite(rec),'rerank_proxy_rewrite'),++idx,'rerank_proxy_rewrite',rec,retRew);
 await chat(upstreamPort,manualPayload(rec,contextBlock(retOrig.chunks,rec)),++idx,'policy_splice_orig_retrieval',rec,retOrig);
 await chat(upstreamPort,manualPayload(rec,contextBlock(retRew.chunks,rec)),++idx,'policy_splice_rewrite_retrieval',rec,retRew);
}
